### ISSUE TITLE
getting some errors

### ISSUE THREAD

**Issue by paulooliveiraa** [dracoapi/dracowalker#17]
###C:\Users\paulo\dracowalker>node -v
v8.9.3

C:\Users\paulo\dracowalker>tsc -v
Version 2.6.2

C:\Users\paulo\dracowalker>node ./bin/app.js
16:54:07 - info: App starting...
16:54:07 - info: go to http://ui.dracoapi.ml/ for ui
16:54:07 - error:  TypeError: Cannot read property 'url' of null
    at ProxyHelper.checkProxy (C:\Users\paulo\dracowalker\bin\lib\proxy.js:95:32)
    at main (C:\Users\paulo\dracowalker\bin\app.js:49:41)
    at Object.<anonymous> (C:\Users\paulo\dracowalker\bin\app.js:243:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
16:54:07 - error: Exiting.

C:\Users\paulo\dracowalker>

could u help me @niicojs ?

**Comment by niicojs** [comment]
can you paste your config file somewhere?
(remove deviceid, login and password)

**Comment by paulooliveiraa** [comment]
https://pastebin.com/QDa4TdXv

here @niicojs

**Comment by niicojs** [comment]
Comment the whole `proxy` if you don't need proxy.  
I'll fix it in code to detect that

**Comment by paulooliveiraa** [comment]
Thnx for the help!
I think it´s working good!

Can u just look to confirm? https://pastebin.com/p4NLe1jn
