### ISSUE TITLE
INCUBATOR_NOT_FOUND error log msg

### ISSUE THREAD

**Issue by mitviet1** [dracoapi/dracowalker#19]
start having this INCUBATOR_NOT_FOUND msg  log constantly.   My acct showed I have a full 12/12 eggs with one perpetual cocoon.  So not sure what's the draco bot is looking/doing when I have no other cocoon available.   Thks for looking into this.  

09:23:40 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\Users\...\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
09:23:40 - error:  __type=FServiceError, args=[], cause=INCUBATOR_NOT_FOUND

**Comment by Nackenschelle** [comment]
login into your game by mobile phone or emulator and check the eggs.
normaly it fixes by itself
got the same error yesterday

**Comment by niicojs** [comment]
fixed in 1.0.4

**Comment by mitviet1** [comment]
Thanks... also FYI, I started to see more often the below 'error' messages
and then the bot just aborted.   Hopefully you can find out what the issue
is.  Thanks again.
-----------------------------------------------
09:37:27 - debug: Map Refresh lat=37.76001194591255, lng=-77.46429803851073
09:37:38 - debug: Map Refresh lat=37.76021123721375, lng=-77.46427797417888
10:46:31 - error:  RequestError: Error: getaddrinfo ENOTFOUND
us.draconiusgo.com us.draconiusgo.com:443
    at new RequestError
(C:\Users\......\dracowalker\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback
(C:\Users\......\dracowalker\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback]
(C:\Users\......\dracowalker\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback
(C:\Users\......\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.onRequestError
(C:\Users\......\dracowalker\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
10:46:37 - error:  Error: Error from server: 401 - Unauthorized
    at Client.call
(C:\Users\......\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
10:46:38 - debug: Map Refresh lat=37.76023156475745, lng=-77.4642771559155
10:46:38 - error:  Error: Error from server: 401 - Unauthorized
    at Client.call
(C:\Users\......\dracowalker\node_modules\draconode\bin\index.js:141:19)
.
10:46:47 - debug: Map Refresh lat=37.76122807895708, lng=-77.46366198912028
10:46:47 - error:  Error: Error from server: 401 - Unauthorized
    at Client.call
(C:\Users\......\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
10:46:47 - error: Too much errors, aborting.
--------------------------------------

**Comment by niicojs** [comment]
that's a network error, it means either your network, proxy or dracionius network has a problem (most likely yours or your proxy)

**Comment by mitviet1** [comment]
ok.  Got it. yeah, I just had to continue monitoring this bot and it was a
bit tiresome :-) so just want to make sure it wasn't anything the bot is
doing.  I hope you got some technical help for other stuff that you want to
enhance w/ the bot.   Wish I could help but I only can program in specific
languages that you may not heard of.   (ABAP programming in ERP system).
 Anyway, I assume you would continue to like for me (or anyone) to use
Github to report issues so this reply will be the last for this particular
issue :-) oooppsss, maybe not.  I just remember to want to let you know
that it seems the Autorelease feature is not working 'consistently' for
some reason.   For example, I have purged the Frogus beast down to one, say
w/ CP = 200 and then after a few hours of running the bot, I see that it
still retained several Frogus that has CP much lower than 200.   And I have
No Frogus in any gym or libraries.  Kind of weird as I do see in the log
that the bot did catch and release Frogus too.  OK, so much for my rant.
 Appreciate your bot always.
