### ISSUE TITLE
 Error: Error during Google login

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#33]
hi folks,
i can t login, no accounts work so far, any idea what can be wrong?
thx for helping

**Comment by nocomp** [comment]
17:10:10 - error:  Error: Error during Google login: BadAuthentication
    at __dirname.getToken.google.oauth (C:\snapshot\dracowalker\node_modules\draconode\bin\lib\google.js:88:28)
    at Request._callback (C:\snapshot\dracowalker\node_modules\gpsoauth\index.js:103:9)
    at Request.init.self.callback (C:\snapshot\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (C:\snapshot\dracowalker\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (C:\snapshot\dracowalker\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
17:10:10 - error: Exiting.

**Comment by niicojs** [comment]
can you login on the real app with the same account?

**Comment by nocomp** [comment]
hi,
yes it works like a charm

**Comment by nocomp** [comment]
as username i tried either username or username@gmail.com both returned same error
hope it can help

**Comment by nocomp** [comment]
here is the log file
18:25:15 - info: go to http://ui.dracoapi.ml/ for ui
18:25:20 - error:  Error: Error during Google login: BadAuthentication
    at __dirname.getToken.google.oauth (C:\snapshot\dracowalker\node_modules\draconode\bin\lib\google.js:88:28)
    at Request._callback (C:\snapshot\dracowalker\node_modules\gpsoauth\index.js:103:9)
    at Request.init.self.callback (C:\snapshot\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (C:\snapshot\dracowalker\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (C:\snapshot\dracowalker\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by nocomp** [comment]
don tunderstand why it looks for a file located C:\snapshot\dracowalker\node_modules\request\request.js:1163:10) there are none c:\snapshot doesn t even exist.
i am using last build for win64 downloaded here with a config file
https://github.com/dracoapi/dracowalker/releases

**Comment by nocomp** [comment]
this is the inux log using the build in the release

nocomp@ubuntu:~/dracowalker$ ./dracowalker data/config.yaml 
09:37:49 - info: App starting...
09:37:49 - info: go to http://ui.dracoapi.ml/ for ui
09:37:52 - error:  Error: Error during Google login: BadAuthentication
    at __dirname.getToken.google.oauth (/snapshot/dracowalker/node_modules/draconode/bin/lib/google.js:88:28)
    at Request._callback (/snapshot/dracowalker/node_modules/gpsoauth/index.js:103:9)
    at Request.init.self.callback (/snapshot/dracowalker/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/snapshot/dracowalker/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/snapshot/dracowalker/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
09:37:52 - error: Exiting.

**Comment by nocomp** [comment]
is there anything i did wrong? 
thxx for helping

**Comment by niicojs** [comment]
The app use a virtual filesystem, `(c:)/snapshots` does not exist, this is expected.
Could you try latest build here: https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts?

**Comment by nocomp** [comment]
oki will try when back home,
thxx a lot

**Comment by nocomp** [comment]
damm :'(

PS E:\dracowalker> .\draco.exe .\data\config.yaml
21:27:21 - info: App starting...
21:27:21 - info: go to http://ui.dracoapi.ml/ for ui
21:27:24 - error:  Error: Error during Google login: BadAuthentication
    at __dirname.getToken.google.oauth (C:\snapshot\dracowalker\node_modules\draconode\bin\lib\google.js:88:28)
    at Request._callback (C:\snapshot\dracowalker\node_modules\gpsoauth\index.js:103:9)
    at Request.init.self.callback (C:\snapshot\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (C:\snapshot\dracowalker\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (C:\snapshot\dracowalker\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
21:27:24 - error: Exiting.
PS E:\dracowalker>

what can be wrong?

**Comment by niicojs** [comment]
don't really know...
do you have multi factor authentication set up?
are you sure config.yaml is correct?

**Comment by nocomp** [comment]
î have a 2 factor auth but it doesnt affect when i log in with the game
do you think i should disable it?

here is the config file
# User credentials
credentials:
  # DEVICE or GOOGLE
  login: GOOGLE
  deviceId: 'XXXX-E35E-4BC8-A4CA-7XXXXXXXX'
  username: 'my-email@gmail.com'
  password: 'password'

# Initial position when starting the app (ex: Paris)
pos:
  lat: 65.94372
  lng: 16.132642

# Speed in km/h (default = auto)
# auto = 90% of run speed from server
speed: 8

# If nothing is set, direct call will be made
# If a proxy is set it will be used (like http://server:8080)
# If 'auto' is set, a proxy from https://www.sslproxies.org will be used
proxy: 
  # url: auto

behavior:
  autorelease: true
  evolveperfect: true
  autoalliance: RED
  incubate: true

gmapKey: xxxxxxxxxxxxxxxxxRfkWYg7IEFMUdaxxxxxxx

inventory:
  MAGIC_BALL_SIMPLE:  40 # apprentice sphere
  MAGIC_BALL_NORMAL:  50 # master sphere
  POTION_HEAL_1: 10 #
  POTION_HEAL_2: 10
  POTION_RESURRECTION_1: 20 # resurecting potion
  RUNE_1: 10
  RUNE_2: 10
  RUNE_3: 10
  FOOD_MORE_DUST: 10 # donut
  FOOD_CALM_DOWN: 10 # Marshmallow
  FOOD_MORE_CANDIES: 10 # ice-cream

router: 
  name: stops
  followroads: true

**Comment by niicojs** [comment]
Yes, try to disable it I guess it comes from that
