### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#49]
Hey i have an issue with the latest dev build

Error Code:
15:31:07 - debug: Using config file config.yaml.
15:31:07 - info: App starting...
15:31:07 - info: Launched from binary, version not found

**Comment by niicojs** [comment]
Where did you download the file from? (appveyor?) and which OS are you using? (linux, windows, macos)

**Comment by Nackenschelle** [comment]
i download the latest build from appveyor
https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts
i use windows 10

**Comment by niicojs** [comment]
Humm, weird. It's working fine with me on the same config.
It means the versionning does not work, but the app is launching fine right?

**Comment by Nackenschelle** [comment]
No the Bot stops and don't do anything.
I will test the latest Build now and give a feedback

**Comment by Nackenschelle** [comment]
Ok latest Version and still don't work

But here is a new Error Code

16:05:49 - error:  RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1024:11)
    at Buffer.readUInt8 (buffer.js:1064:5)
    at Deserializer.readByte (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:21:33)
    at Deserializer.readStaticObject (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:177:25)
    at Deserializer.readObject (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:136:25)
    at Deserializer.readStaticMap (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:122:30)
    at FConfig.deserialize (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\objects.js:1003:53)
    at Deserializer.readStaticObject (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:181:17)
    at Deserializer.readDynamicObject (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:200:25)
    at Deserializer.deserialize (F:\snapshot\dracowalker\node_modules\draconode\bin\draco\deserializer.js:204:21)
    at Client.call (F:\snapshot\dracowalker\node_modules\draconode\bin\index.js:150:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by niicojs** [comment]
Could you paste the full log?

**Comment by niicojs** [comment]
Also, the error just above was a build issue, should be correct now

**Comment by Nackenschelle** [comment]
i will test it tomorrow.
not home for today
thanks in advance

**Comment by Nackenschelle** [comment]
update works fine 
issue can be closed
