### ISSUE TITLE
Account getting banned

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#50]
ola,
here is a new type of error i get often after running the bot quite a bit, 3-4 hours

19:31:53 - warn: Unhandled object in map update: FQuestUpdate
19:32:04 - error: Error: Error from server: 412 - Precondition Failed
at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:143:19)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)
19:32:04 - error: __type=FServiceError, args=[], cause=SESSION_GONE
PS D:\docs\dracowalker>

**Comment by niicojs** [comment]
It seems the session has been invalidated by the server.
This can happend if bot is running too long or if you log in elsewhere (on your phone for example).

I'll put on my todo list to do auto relogin.

**Comment by nocomp** [comment]
hmm good thought, i never used my bot accounts on mobile, so surely it s cause of too long connection.
mays be a schedduler would be great.
thxx for the effort

**Comment by xandymp** [comment]
I'm getting this error too. Started this morning after doing some tests with the ui item use.

**Comment by xandymp** [comment]
I think I found out the problem.
![screenshot_20180306-101916](https://user-images.githubusercontent.com/19960976/37036133-7a870cdc-212d-11e8-9cd7-ad8a12131727.jpg)

**Comment by nocomp** [comment]
weird, none of mine are banned, i ll check in the coming days what happend

**Comment by xandymp** [comment]
Just because I had a Keeper with IV 6/6 and CP 2970.
Guess I'll need to start over and lookout for the way I use the bot.

**Comment by xandymp** [comment]
I created a new account and after 20min I got this message
`error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:143:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
`error:  __type=FServiceError, args=[AutoBySuspicion], cause=USER_BANNED`

**Comment by nocomp** [comment]
3:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
00:17:04 - error:  __type=FServiceError, args=[AutoBySuspicion], cause=USER_BANNED
00:17:04 - error: Too much errors, 


it s official now , botting is flagged :'(

i guess last update changed something

**Comment by nocomp** [comment]
10 min

**Comment by niicojs** [comment]
could you test last version?

**Comment by nocomp** [comment]
I ve used last linux64 released got banned after 10 min

**Comment by niicojs** [comment]
I published a new dev version if you have an account to spare

**Comment by nocomp** [comment]
oki i ll try this evening
thxx a lot

**Comment by nocomp** [comment]
can t download https://ci.appveyor.com/api/buildjobs/vik90ndml95d856d/artifacts/dist%2Fdracowalker-win-x64.exe it says failed ntwork error

always get these error on this host

**Comment by niicojs** [comment]
appveyor does that something, you just have to wait and keep trying

**Comment by nocomp** [comment]
ok

**Comment by nocomp** [comment]
running since 20 mins, logs so far
PS E:\dracowalker> .\draco.exe .\data\config.yaml
16:47:18 - info: App starting...
16:47:18 - info: Launched from binary, version dev-1.0.74
16:47:30 - info: Go to http://ui.dracoapi.ml/ for ui
16:47:33 - info: Client started...
16:48:13 - info: Stop spun!
16:48:50 - info: Potty caught!
16:51:04 - info: Stop spun!
16:51:56 - error:  RequestError: Error: connect ETIMEDOUT 104.20.230.58:443
    at new RequestError (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.module.exports.plumbing.callback (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.init.self.callback (C:\snapshot\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.onRequestError (C:\snapshot\dracowalker\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
16:52:01 - error:  RequestError: Error: connect ETIMEDOUT 104.20.230.58:443
    at new RequestError (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.module.exports.plumbing.callback (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.init.self.callback (C:\snapshot\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.onRequestError (C:\snapshot\dracowalker\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
16:55:29 - info: Stop spun!
16:55:35 - info: Berrydillo caught!
16:55:41 - info: Start hatching a 5km egg.
16:55:51 - info: Stop spun!
16:56:25 - info: Stop spun!
16:56:31 - info: Potty caught!
16:56:47 - info: Stop spun!
16:58:39 - info: Potty caught!
17:00:02 - info: Potty caught!
17:01:12 - info: Rabby caught!
17:02:17 - info: Chest found!
17:04:03 - info: Stop spun!

**Comment by nocomp** [comment]
after 1h15 it frozed, no error log, ctrl c and resart, so far so good

**Comment by nocomp** [comment]
hmm gets frozen again, need to restart it, weird

**Comment by niicojs** [comment]
frozen how?

**Comment by nocomp** [comment]
peg not moving, no more action log like creature caught or stop spun.
just checked now it has work almost all nite froze at 5 am

**Comment by nocomp** [comment]
other log just happening now
08:33:54 - error:  RequestError: Error: connect ETIMEDOUT 104.20.230.58:443
    at new RequestError (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.module.exports.plumbing.callback (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\snapshot\dracowalker\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.init.self.callback (C:\snapshot\dracowalker\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.onRequestError (C:\snapshot\dracowalker\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by niicojs** [comment]
the last one is a network issue on your side (or on your proxy side).
I'll think about the frozen thing
