### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by VirtualS031** [dracoapi/dracowalker#57]
12:36:53 - info: App starting...
12:36:53 - info: Launched from source
12:36:53 - info: Go to http://ui.dracoapi.ml/ for ui
12:36:56 - info: Client started...
12:36:58 - error:  TypeError: Cannot read property 'low' of undefined
    at Function.fromValue (C:\projects\dracowalker\node_modules\long\src\long.js:286:25)
    at Serializer.writeInt64 (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:94:24)
    at FUpdateRequest.serialize (C:\projects\dracowalker\node_modules\draconode\bin\draco\objects.js:2232:20)
    at Serializer.writeStaticObject (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:221:26)
    at Serializer.writeDynamicObject (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:256:18)
    at Serializer.writeObject (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:187:25)
    at Serializer.writeStaticArray (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:128:18)
    at Serializer.writeDynamicObject (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:251:22)
    at Serializer.serialize (C:\projects\dracowalker\node_modules\draconode\bin\draco\serializer.js:261:14)
    at Client.call (C:\projects\dracowalker\node_modules\draconode\bin\index.js:116:35)
    at Client.getMapUpdate (C:\projects\dracowalker\node_modules\draconode\bin\index.js:333:37)
    at mapRefresh (C:\projects\dracowalker\bin\app.js:259:33)
    at main (C:\projects\dracowalker\bin\app.js:99:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by niicojs** [comment]
try latest (version > dev-1.0.85)

**Comment by VirtualS031** [comment]
work now. Good work niicojs
