### ISSUE TITLE
still error on startup 

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#59]
latest dev build:
11:42:52 - error:  Error: This API project was not found. This API project may have been deleted.
    at HumanRouter.generateWaypoint (C:\snapshot\dracowalker\bin\lib\router\BaseRouter.js:28:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Nackenschelle** [comment]
ok i will test it

**Comment by Nackenschelle** [comment]
still same error with new gmaps key
