### ISSUE TITLE
update.chests

### ISSUE THREAD

**Issue by ElliotRobot20** [dracoapi/dracowalker#6]
14:05:11 - error:  TypeError: update.chests is not iterable
    at Player.openChests (C:\GitFolders\dracowalkerElliot\bin\lib\player.js:213:40)
    at mapRefresh (C:\GitFolders\dracowalkerElliot\bin\app.js:190:18)
    at <anonymous>
14:05:11 - error: Exiting.

**Comment by niicojs** [comment]
fixed
