### ISSUE TITLE
evolved dont work

### ISSUE THREAD

**Issue by Tinoxy** [dracoapi/dracowalker#69]
### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications
  - Version: version dev-1.0.95
  - Platform: windows

### Logs
06:56:03 - info: Perfect Berrydillo evolved to Shamurf
06:56:06 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:160:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
06:56:06 - error:  __type=FServiceError, args=[], cause=SERVER_ERROR

**Comment by niicojs** [comment]
do you have that for all evolve or only some oh them?

**Comment by niicojs** [comment]
more importantly, did you evolve multiple creature on a row? (the same type)
