### ISSUE TITLE
Auto Complete Tutorial

### ISSUE THREAD

**Issue by sirlygo** [dracoapi/dracowalker#9]
would be nice to have it auto complete tutorial as of right now if tutorial isnt complete you will get this error message 

14:18:58 - info: go to http://ui.dracoapi.ml/ for ui
14:19:01 - error:  Error: Unable to login
    at main (C:\Users\****\Desktop\git-sdk-64-master\git-sdk-64-master\dracowalker1\bin\app.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
14:19:01 - error: Exiting.

**Comment by niicojs** [comment]
Yes. If someone can help me mitm this state (on the real app on through the api) or give me an account to play with I'll digg into it.

**Comment by sirlygo** [comment]
do you need a never played on account?

**Comment by niicojs** [comment]
yes, ideally in the same state yours was
